---
language: ruby
notifications:
  email:
  - drbrain@segment7.net
  - ljjarvis@gmail.com
  - knu@idaemons.org

# bundler is missing for jruby-head in travis-ci
# https://github.com/travis-ci/travis-ci/issues/5861
before_install:
  - gem install --conservative bundler -v'1.13.7'

script: rake test

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head

env:
  global:
    - JRUBY_OPTS="--debug"
