---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
  - ljjarvis@gmail.com
  - knu@idaemons.org
rvm:
- 1.9.3
- 2.0.0
- ruby-head
- jruby-19mode
- jruby-head
- rbx-19mode
script: rake travis
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-19mode
